export const sample_foods = [
    {
        // id: "1",
        name: "Pizza",
        cookTime: "30 mins",
        price: 10,
        favorite: false,
        origin: ["New York"],
        stars: 5,
        imageUrl: 'Pizza-Dough_1.jpg',
        tags: ["pizza", "italian", "cheese", "pepperoni", "tomato", "dough", "lunch", "dinner", "appetizers"],
      },
      {
        // id: "2",
        name: "Philly Cheesesteak",
        cookTime: "20 mins",
        price: 15,
        favorite: true,
        origin: ["Philadelphia", "Persia", "Italy", "Greece", "China"],
        stars: 5,
        imageUrl: 'Philly-Cheesesteak-2.jpg',
        tags: ["SlowFood", "Lunch", "apetizers"],
      },
      {
        // id: "3",
        name: "Gourmet Hamburger",
        cookTime: "18 mins",
        price: 22,
        favorite: false,
        origin: ["Germany", "USA"],
        stars: 4,
        imageUrl: 'loaded-burgers-featured-3.jpg',
        tags: ["SlowFood", "Hamburger", "Lunch", "Dinner", "Beef"],
      },
      {
        // id: "4",
        name: "Loaded French Fries",
        cookTime: "10 mins",
        price: 8,
        favorite: true,
        origin: ["Belgium", "France", "USA"],
        stars: 5,
        imageUrl: 'cheese-fries-4.jpg',
        tags: [
          "FastFood",
          "Fry",
          "Lunch",
          "Dinner",
          "Potato",
          "Cheese",
          "Bacon",
          "Sour Cream",
          "Chives",
          "Jalapeno",
          "appetizers",
        ],
      },
      {
        // id: "5",
        name: "Dozen Delish Chicken Wings",
        cookTime: "12 mins",
        price: 14,
        favorite: false,
        origin: ["USA", "Africa"],
        stars: 5,
        imageUrl: 'delish-fried-chicken-wings-5.jpg',
        tags: [
          "appetizers",
          "Fry",
          "Chicken",
          "Lunch",
          "Dinner",
          "FastFood",
          "Wings",
          "Hot",
          "Spicy",
        ],
      },
      {
        // id: "6",
        name: "Grilled Chicken Caesar Salad",
        cookTime: "5 mins",
        price: 12,
        favorite: true,
        origin: ["USA", "Italy"],
        stars: 3,
        imageUrl: 'grilled-caesar-chicken-salad-6.jpg',
        tags: ["Lunch", "Dinner", "Salad", "Chicken", "Caesar", "apetizers"],
      },
    ];
    
    export const sample_tags = [
      { name: "All", count: 6 },
      { name: "FastFood", count: 3 },
      { name: "Pizza", count: 1 },
      { name: "Lunch", count: 4 },
      { name: "SlowFood", count: 3 },
      { name: "Hamburger", count: 1 },
      { name: "Fry", count: 2 },
      { name: "Salad", count: 1 },
    ];

export const sample_users = [
  {
    // id: "1",
    name: "Aaron Rodgers",
    email: "A.Rodgers@gmail.com",
    password: "123456",
    address: "123 Main St",
    city: "New York",
    state: "NY",
    zip: "10001",
    phone: "212-555-1212",
    isAdmin: false,
  },
  {
    // 87/id: "2",
    name: "Lex Luthor",
    email: "LexCorpceo@gmail.com",
    password: "ihateSuperman1234",
    address: "123 Main St",
    city: "Metropolis",
    state: "NY",
    zip: "10001",
    phone: "212-555-1213",
    isAdmin: false,
  },
  {
    // id: "3",
    name: "Bruce Wayne",
    email: "theDarkKnight@gmail.com",
    password: "12joker34",
    address: "1938 Wayne Manor",
    city: "Gotham",
    state: "NY",
    zip: "10002",
    phone: "212-555-1938",
    isAdmin: true,
  },
  {
    // id: "4",
    name: "Clark Kent",
    email: "ManofSteel@gmail.com",
    password: "12doomsday34",
    address: "1938 Kent Farm",
    city: "Smallville",
    state: "KS",
    zip: "10003",
    phone: "318-555-1935",
    isAdmin: true,
  },
  {
    // id: "5",
    name: "Peter Parker",
    email: "Spidey@gmail.com",
    password: "12venom34",
    address: "1938 Parker House",
    city: "Queens",
    state: "NY",
    zip: "10004",
    phone: "718-555-1610",
    isAdmin: false,
  },
  {
    // id: "6",
    name: "Tony Stark",
    email: "playboy@gmail.com",
    password: "12ironman34",
    address: "1938 Stark Tower",
    city: "Manhattan",
    state: "NY",
    zip: "10005",
    phone: "212-555-1938",
    isAdmin: false,
  },
  {
    // id: "7",
    name: "Steve Rogers",
    email: "Captain@gmail.com",
    password: "12america34",
    address: "1945 Rogers House",
    city: "Brooklyn",
    state: "NY",
    zip: "10006",
    phone: "212-555-1945",
    isAdmin: false,
  },
  {
    // id: "8",
    name: "Bruce Banner",
    email: "GreenMachine@gmail.com",
    password: "12hulk34",
    address: "Unkown",
    city: "Unknown",
    state: "California",
    zip: "10007",
    phone: "Unknown",
    isAdmin: false,
  },
  {
    // id: "9",
    name: "Natasha Romanoff",
    email: "Blkwidow@gmail.com",
    password: "12russia34",
    address: "1610 Avengers Tower",
    city: "Bethesda",
    state: "MD",
    zip: "10008",
    phone: "Unknown",
    isAdmin: false,
  },
  {
    // id: "10",
    name: "Thor Odinson",
    email: "strongestAvenger@gmail.com",
    password: "12mjolnir34",
    address: "Asgard",
    city: "Asgard",
    state: "Asgard",
    zip: "10009",
    phone: "Unknown",
    isAdmin: false,
  },
];

